name: ci

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    env:
      TZ: Asia/Tokyo

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v4.4.0

      - name: Setup node env 🏗
        uses: actions/setup-node@v4
        with:
          node-version-file: '.node-version'
          cache: 'pnpm'

      - name: Install dependencies 👨🏻‍💻
        run: pnpm install --frozen-lockfile

      - name: Run ESLint
        run:  |
          pnpm lint
          pnpm test:custom-eslint-rules

      - name: Run Tests for Browser environment
        run: pnpm test:browser

      - name: Run Tests form Node.js environment
        run: pnpm test:node

      - name: Run build
        run: pnpm build
